-- 基本設定テーブル
-- テーブルの削除
DROP TABLE IF EXISTS BASIC_SETTING_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS BASIC_SETTING_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE BASIC_SETTING_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE BASIC_SETTING_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('BASIC_SETTING_INFO_SEQ'),
    COMPANY_NAME VARCHAR(255),
    COMPANY_LOGO VARCHAR(255),
    ADDRESS_1 VARCHAR(255),
    ADDRESS_2 VARCHAR(255),
    BANK_NAME VARCHAR(255),
    BRANCH_NAME VARCHAR(255),
    BRANCH_CODE VARCHAR(50),
    ACCOUNT_FLAG VARCHAR(1),
    ACCOUNT_NUMBER VARCHAR(50),
    INVOICE_NUMBER VARCHAR(50),
    CONSUMPTION_TAX_RATE VARCHAR(50),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- 注釈の追加
COMMENT ON COLUMN BASIC_SETTING_INFO.COMPANY_NAME IS '会社名';
COMMENT ON COLUMN BASIC_SETTING_INFO.COMPANY_LOGO IS '会社ロゴ';
COMMENT ON COLUMN BASIC_SETTING_INFO.ADDRESS_1 IS '住所1';
COMMENT ON COLUMN BASIC_SETTING_INFO.ADDRESS_2 IS '住所2';
COMMENT ON COLUMN BASIC_SETTING_INFO.BANK_NAME IS '銀行名';
COMMENT ON COLUMN BASIC_SETTING_INFO.BRANCH_NAME IS '支店名';
COMMENT ON COLUMN BASIC_SETTING_INFO.BRANCH_CODE IS '支店コード';
COMMENT ON COLUMN BASIC_SETTING_INFO.ACCOUNT_FLAG IS '口座フラグ';
COMMENT ON COLUMN BASIC_SETTING_INFO.ACCOUNT_NUMBER IS '口座番号';
COMMENT ON COLUMN BASIC_SETTING_INFO.INVOICE_NUMBER IS 'インボイス番号';
COMMENT ON COLUMN BASIC_SETTING_INFO.CONSUMPTION_TAX_RATE IS '消費税率';
COMMENT ON COLUMN BASIC_SETTING_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN BASIC_SETTING_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN BASIC_SETTING_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN BASIC_SETTING_INFO.LAST_UPDATER IS '最終更新者';


-- 取引先情報テーブル
-- テーブルの削除
DROP TABLE IF EXISTS BUSINESS_PARTNER_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS BUSINESS_PARTNER_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE BUSINESS_PARTNER_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE BUSINESS_PARTNER_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('BUSINESS_PARTNER_INFO_SEQ'),
    COMPANY_NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- 注釈の追加
COMMENT ON COLUMN BUSINESS_PARTNER_INFO.COMPANY_NAME IS '会社名';
COMMENT ON COLUMN BUSINESS_PARTNER_INFO.ADDRESS IS '住所';
COMMENT ON COLUMN BUSINESS_PARTNER_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN BUSINESS_PARTNER_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN BUSINESS_PARTNER_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN BUSINESS_PARTNER_INFO.LAST_UPDATER IS '最終更新者';


-- 取引先店舗情報テーブル
-- テーブルの削除
DROP TABLE IF EXISTS BUSINESS_PARTNER_STORE CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS BUSINESS_PARTNER_STORE_SEQ;

-- シークエンスの作成
CREATE SEQUENCE BUSINESS_PARTNER_STORE_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE BUSINESS_PARTNER_STORE (
    ID INT PRIMARY KEY DEFAULT nextval('BUSINESS_PARTNER_STORE_SEQ'),
    PARTNER_ID INT,
    STORE_NAME VARCHAR(255),
    ESTIMATE_CC_FLAG VARCHAR(1),
    SAME_AS_ESTIMATE_FLAG VARCHAR(1),
    BILLING_CC_FLAG VARCHAR(1),
    STORE_ADDRESS VARCHAR(255),
    SAME_AS_WEEKDAYS_FLAG VARCHAR(1),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- 注釈の追加
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.PARTNER_ID IS '取引先ID';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.STORE_NAME IS '店舗名';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.ESTIMATE_CC_FLAG IS '見積Cc不要フラグ';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.SAME_AS_ESTIMATE_FLAG IS '見積送付先と同じフラグ';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.BILLING_CC_FLAG IS '請求Cc不要フラグ';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.STORE_ADDRESS IS '店舗アドレス';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.SAME_AS_WEEKDAYS_FLAG IS '平日と同じフラグ';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.CREATION_DATE IS '作成日';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.CREATOR IS '作成者';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN BUSINESS_PARTNER_STORE.LAST_UPDATER IS '最終更新者';

-- 外鍵の追加
ALTER TABLE BUSINESS_PARTNER_STORE ADD CONSTRAINT FK_PARTNER_ID FOREIGN KEY (PARTNER_ID) REFERENCES BUSINESS_PARTNER_INFO(ID);


----------------------------------------------------
-- 単価情報
-- テーブルの削除
DROP TABLE IF EXISTS UNIT_PRICE_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS UNIT_PRICE_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE UNIT_PRICE_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE UNIT_PRICE_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('UNIT_PRICE_INFO_SEQ'),
    PARTNER_STORE_ID INT,
    ORDER_TYPE VARCHAR(255),
    UNIT_PRICE VARCHAR(255),
    WEEKDAY_FLAG VARCHAR(1),
    WEEKEND_FLAG VARCHAR(1),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);
-- 外鍵の追加例
ALTER TABLE UNIT_PRICE_INFO ADD CONSTRAINT FK_PARTNER_STORE_ID FOREIGN KEY (PARTNER_STORE_ID) REFERENCES BUSINESS_PARTNER_INFO(ID);

-- テーブルのコメント追加
COMMENT ON COLUMN UNIT_PRICE_INFO.PARTNER_STORE_ID IS '取引先店舗ID';
COMMENT ON COLUMN UNIT_PRICE_INFO.ORDER_TYPE IS 'オーダー';
COMMENT ON COLUMN UNIT_PRICE_INFO.UNIT_PRICE IS '単価';
COMMENT ON COLUMN UNIT_PRICE_INFO.WEEKDAY_FLAG IS '平日フラグ';
COMMENT ON COLUMN UNIT_PRICE_INFO.WEEKEND_FLAG IS '週末フラグ';
COMMENT ON COLUMN UNIT_PRICE_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN UNIT_PRICE_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN UNIT_PRICE_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN UNIT_PRICE_INFO.LAST_UPDATER IS '最終更新者';

-- 案件マスタ情報
-- テーブルの削除
DROP TABLE IF EXISTS MATTER_MASTER_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS MATTER_MASTER_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE MATTER_MASTER_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE MATTER_MASTER_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('MATTER_MASTER_INFO_SEQ'),
    NO INT,
    REJECTION VARCHAR(255),
    STAFF_OPERATION_DETAILS VARCHAR(255),
    AGENT_BY_NAME VARCHAR(255),
    VAR_DATE VARCHAR(255),
    WEEKDAY_WEEKEND VARCHAR(1),
    BUSINESS_TRIP VARCHAR(1),
    EVENT_LOCATION VARCHAR(255),
    LOCATION_RESERVATION VARCHAR(255),
    SB_STORE VARCHAR(255),
    AGENT VARCHAR(255),
    ORDER_TYPE VARCHAR(255),
    BY_NAME VARCHAR(255),
    SALES_MEMO VARCHAR(255),
    ASSIGN_MEMO VARCHAR(255),
    UNIT_PRICE VARCHAR(255),
    DAYS INT,
    SALES VARCHAR(255),
    CREATION_POSSIBLE VARCHAR(1),
    ESTIMATE_SENT VARCHAR(1),
    BILL_SENT VARCHAR(1),
    JUDGMENT VARCHAR(1),
    EXISTENCE VARCHAR(1),
    AGENT_COMPANY_NAME VARCHAR(255),
    AGENT_PERSON_IN_CHARGE VARCHAR(255),
    IMPLEMENTATION_SCHEDULE DATE,
    INTEGRATION_FLAG VARCHAR(1),
    MONTHLY_PAYMENT_FLAG VARCHAR(1),
    EXECUTION_FLAG VARCHAR(1),
    ITEM_NAME VARCHAR(255),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- テーブルのコメント追加
COMMENT ON COLUMN MATTER_MASTER_INFO.NO IS 'No';
COMMENT ON COLUMN MATTER_MASTER_INFO.REJECTION IS 'お断り';
COMMENT ON COLUMN MATTER_MASTER_INFO.STAFF_OPERATION_DETAILS IS 'スタッフ向け稼働詳細';
COMMENT ON COLUMN MATTER_MASTER_INFO.AGENT_BY_NAME IS '代理店向けバイネーム';
COMMENT ON COLUMN MATTER_MASTER_INFO.VAR_DATE IS '日付';
COMMENT ON COLUMN MATTER_MASTER_INFO.WEEKDAY_WEEKEND IS '平日/週末';
COMMENT ON COLUMN MATTER_MASTER_INFO.BUSINESS_TRIP IS '出張';
COMMENT ON COLUMN MATTER_MASTER_INFO.EVENT_LOCATION IS 'イベント実施場所';
COMMENT ON COLUMN MATTER_MASTER_INFO.LOCATION_RESERVATION IS '場所取り';
COMMENT ON COLUMN MATTER_MASTER_INFO.SB_STORE IS 'SB開催店舗';
COMMENT ON COLUMN MATTER_MASTER_INFO.AGENT IS '代理店';
COMMENT ON COLUMN MATTER_MASTER_INFO.ORDER_TYPE IS 'オーダー';
COMMENT ON COLUMN MATTER_MASTER_INFO.BY_NAME IS 'バイネーム';
COMMENT ON COLUMN MATTER_MASTER_INFO.SALES_MEMO IS '営業担当メモ';
COMMENT ON COLUMN MATTER_MASTER_INFO.ASSIGN_MEMO IS 'アサイン担当メモ';
COMMENT ON COLUMN MATTER_MASTER_INFO.UNIT_PRICE IS '単価';
COMMENT ON COLUMN MATTER_MASTER_INFO.DAYS IS '日数';
COMMENT ON COLUMN MATTER_MASTER_INFO.SALES IS '売り上げ';
COMMENT ON COLUMN MATTER_MASTER_INFO.CREATION_POSSIBLE IS '作成可';
COMMENT ON COLUMN MATTER_MASTER_INFO.ESTIMATE_SENT IS '見積送付済';
COMMENT ON COLUMN MATTER_MASTER_INFO.BILL_SENT IS '請求送付済';
COMMENT ON COLUMN MATTER_MASTER_INFO.JUDGMENT IS '判定';
COMMENT ON COLUMN MATTER_MASTER_INFO.EXISTENCE IS '有無';
COMMENT ON COLUMN MATTER_MASTER_INFO.AGENT_COMPANY_NAME IS '代理店会社名';
COMMENT ON COLUMN MATTER_MASTER_INFO.AGENT_PERSON_IN_CHARGE IS '代理店担当者';
COMMENT ON COLUMN MATTER_MASTER_INFO.IMPLEMENTATION_SCHEDULE IS '実施日程';
COMMENT ON COLUMN MATTER_MASTER_INFO.INTEGRATION_FLAG IS '統合フラグ';
COMMENT ON COLUMN MATTER_MASTER_INFO.MONTHLY_PAYMENT_FLAG IS '月支払いフラグ';
COMMENT ON COLUMN MATTER_MASTER_INFO.EXECUTION_FLAG IS '実行済みフラグ';
COMMENT ON COLUMN MATTER_MASTER_INFO.ITEM_NAME IS '品目名';
COMMENT ON COLUMN MATTER_MASTER_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN MATTER_MASTER_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN MATTER_MASTER_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN MATTER_MASTER_INFO.LAST_UPDATER IS '最終更新者';

----------------------------------------------------------
-- 見積情報
-- テーブルの削除
DROP TABLE IF EXISTS ESTIMATION_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS ESTIMATION_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE ESTIMATION_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE ESTIMATION_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('ESTIMATION_INFO_SEQ'),
    NO INT,
    REJECTION VARCHAR(255),
    STAFF_OPERATION_DETAILS VARCHAR(255),
    AGENT_BY_NAME VARCHAR(255),
    DATE DATE,
    WEEKDAY_WEEKEND VARCHAR(1),
    BUSINESS_TRIP VARCHAR(1),
    EVENT_LOCATION VARCHAR(255),
    LOCATION_RESERVATION VARCHAR(1),
    SB_STORE VARCHAR(255),
    AGENT VARCHAR(255),
    ORDER_TYPE VARCHAR(255),
    BY_NAME VARCHAR(255),
    SALES_MEMO VARCHAR(255),
    ASSIGN_MEMO VARCHAR(255),
    UNIT_PRICE VARCHAR(255),
    DAYS INT,
    SALES VARCHAR(255),
    CREATION_POSSIBLE VARCHAR(1),
    ESTIMATE_SENT VARCHAR(1),
    BILL_SENT VARCHAR(1),
    JUDGMENT VARCHAR(1),
    EXISTENCE VARCHAR(1),
    AGENT_COMPANY_NAME VARCHAR(255),
    AGENT_PERSON_IN_CHARGE VARCHAR(255),
    IMPLEMENTATION_SCHEDULE DATE,
    INTEGRATION_FLAG VARCHAR(1),
    MONTHLY_PAYMENT_FLAG VARCHAR(1),
    EXECUTION_FLAG VARCHAR(1),
    ITEM_NAME VARCHAR(255),
    COUNT INT,
    MASTER_ID INT,
    SENT_FLAG VARCHAR(1),
    PAGE_DIVISION_1 VARCHAR(1),
    PAGE_DIVISION_2 VARCHAR(1),
    TAX_EXEMPT VARCHAR(1),
    EMAIL_CREATION_ID INT,
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- テーブルのコメント追加
COMMENT ON COLUMN ESTIMATION_INFO.NO IS 'No';
COMMENT ON COLUMN ESTIMATION_INFO.REJECTION IS 'お断り';
COMMENT ON COLUMN ESTIMATION_INFO.STAFF_OPERATION_DETAILS IS 'スタッフ向け稼働詳細';
COMMENT ON COLUMN ESTIMATION_INFO.AGENT_BY_NAME IS '代理店向けバイネーム';
COMMENT ON COLUMN ESTIMATION_INFO.DATE IS '日付';
COMMENT ON COLUMN ESTIMATION_INFO.WEEKDAY_WEEKEND IS '平日/週末';
COMMENT ON COLUMN ESTIMATION_INFO.BUSINESS_TRIP IS '出張';
COMMENT ON COLUMN ESTIMATION_INFO.EVENT_LOCATION IS 'イベント実施場所';
COMMENT ON COLUMN ESTIMATION_INFO.LOCATION_RESERVATION IS '場所取り';
COMMENT ON COLUMN ESTIMATION_INFO.SB_STORE IS 'SB開催店舗';
COMMENT ON COLUMN ESTIMATION_INFO.AGENT IS '代理店';
COMMENT ON COLUMN ESTIMATION_INFO.ORDER_TYPE IS 'オーダー';
COMMENT ON COLUMN ESTIMATION_INFO.BY_NAME IS 'バイネーム';
COMMENT ON COLUMN ESTIMATION_INFO.SALES_MEMO IS '営業担当メモ';
COMMENT ON COLUMN ESTIMATION_INFO.ASSIGN_MEMO IS 'アサイン担当メモ';
COMMENT ON COLUMN ESTIMATION_INFO.UNIT_PRICE IS '単価';
COMMENT ON COLUMN ESTIMATION_INFO.DAYS IS '日数';
COMMENT ON COLUMN ESTIMATION_INFO.SALES IS '売り上げ';
COMMENT ON COLUMN ESTIMATION_INFO.CREATION_POSSIBLE IS '作成可';
COMMENT ON COLUMN ESTIMATION_INFO.ESTIMATE_SENT IS '見積送付済';
COMMENT ON COLUMN ESTIMATION_INFO.BILL_SENT IS '請求送付済';
COMMENT ON COLUMN ESTIMATION_INFO.JUDGMENT IS '判定';
COMMENT ON COLUMN ESTIMATION_INFO.EXISTENCE IS '有無';
COMMENT ON COLUMN ESTIMATION_INFO.AGENT_COMPANY_NAME IS '代理店会社名';
COMMENT ON COLUMN ESTIMATION_INFO.AGENT_PERSON_IN_CHARGE IS '代理店担当者';
COMMENT ON COLUMN ESTIMATION_INFO.IMPLEMENTATION_SCHEDULE IS '実施日程';
COMMENT ON COLUMN ESTIMATION_INFO.INTEGRATION_FLAG IS '統合フラグ';
COMMENT ON COLUMN ESTIMATION_INFO.MONTHLY_PAYMENT_FLAG IS '月支払いフラグ';
COMMENT ON COLUMN ESTIMATION_INFO.EXECUTION_FLAG IS '実行済みフラグ';
COMMENT ON COLUMN ESTIMATION_INFO.ITEM_NAME IS '品目名';
COMMENT ON COLUMN ESTIMATION_INFO.COUNT IS '件数';
COMMENT ON COLUMN ESTIMATION_INFO.MASTER_ID IS '案件マスタID';
COMMENT ON COLUMN ESTIMATION_INFO.SENT_FLAG IS '送信済みフラグ';
COMMENT ON COLUMN ESTIMATION_INFO.PAGE_DIVISION_1 IS 'ページ分け1';
COMMENT ON COLUMN ESTIMATION_INFO.PAGE_DIVISION_2 IS 'ページ分け2';
COMMENT ON COLUMN ESTIMATION_INFO.TAX_EXEMPT IS '非課税';
COMMENT ON COLUMN ESTIMATION_INFO.EMAIL_CREATION_ID IS 'メール作成ID';
COMMENT ON COLUMN ESTIMATION_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN ESTIMATION_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN ESTIMATION_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN ESTIMATION_INFO.LAST_UPDATER IS '最終更新者';


-- 見積請求作成情報
-- テーブルの削除
DROP TABLE IF EXISTS QUOTATION_CLAIM_CREATION_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS QUOTATION_CLAIM_CREATION_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE QUOTATION_CLAIM_CREATION_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE QUOTATION_CLAIM_CREATION_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('QUOTATION_CLAIM_CREATION_INFO_SEQ'),
    SUBJECT_1 VARCHAR(255),
    BED VARCHAR(255),
    SUBJECT_2 VARCHAR(255),
    MAIN_TEXT TEXT,
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- テーブルのコメント追加
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.SUBJECT_1 IS '件名1';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.BED IS 'ベッダ';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.SUBJECT_2 IS '件名2';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.MAIN_TEXT IS '本文';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN QUOTATION_CLAIM_CREATION_INFO.LAST_UPDATER IS '最終更新者';


-- PDF作成情報
-- テーブルの削除
DROP TABLE IF EXISTS PDF_CREATION_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS PDF_CREATION_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE PDF_CREATION_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE PDF_CREATION_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('PDF_CREATION_INFO_SEQ'),
    URL VARCHAR(255),
    ESTIMATE_CLAIM_CREATION_ID INT,
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- 外鍵の追加例
ALTER TABLE PDF_CREATION_INFO ADD CONSTRAINT FK_ESTIMATE_CLAIM_CREATION_ID FOREIGN KEY (ESTIMATE_CLAIM_CREATION_ID) REFERENCES QUOTATION_CLAIM_CREATION_INFO(ID);

-- テーブルのコメント追加
COMMENT ON COLUMN PDF_CREATION_INFO.URL IS 'URL';
COMMENT ON COLUMN PDF_CREATION_INFO.ESTIMATE_CLAIM_CREATION_ID IS '見積請求作成ID';
COMMENT ON COLUMN PDF_CREATION_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN PDF_CREATION_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN PDF_CREATION_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN PDF_CREATION_INFO.LAST_UPDATER IS '最終更新者';

-- 見積請求設定情報
-- テーブルの削除
DROP TABLE IF EXISTS QUOTATION_CLAIM_SETTING_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS QUOTATION_CLAIM_SETTING_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE QUOTATION_CLAIM_SETTING_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE QUOTATION_CLAIM_SETTING_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('QUOTATION_CLAIM_SETTING_INFO_SEQ'),
    FORMAT VARCHAR(255),
    ISSUANCE_RULE VARCHAR(255),
    ITEM_NAME_RULE VARCHAR(255),
    DUE_MONTH_STATUS INT,
    DUE_MONTH INT,
    DUE_DATE_STATUS INT,
    DUE_DATE INT,
    WEEKEND_PREVIOUS_STATUS INT,
    WEEKEND_NEXT_STATUS INT,
    WEEKEND_IGNORE_STATUS INT,
    EMAIL_CREATION_RULE VARCHAR(255),
    SAVE_LOCATION VARCHAR(255),
    CLIENT_COMPANY_NAME VARCHAR(255),
    CLIENT_ESTIMATE_DESTINATION VARCHAR(255),
    TYPE_FLAG VARCHAR(1),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- テーブルのコメント追加
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.FORMAT IS 'フォーマット';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.ISSUANCE_RULE IS '発番ルール';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.ITEM_NAME_RULE IS '品目名記載ルール';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.DUE_MONTH_STATUS IS '振込期日月ステータス';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.DUE_MONTH IS '振込期日月';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.DUE_DATE_STATUS IS '振込期日日付ステータス';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.DUE_DATE IS '振込期日日付';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.WEEKEND_PREVIOUS_STATUS IS '土日祝ステータス前営業日';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.WEEKEND_NEXT_STATUS IS '土日祝ステータス後営業日';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.WEEKEND_IGNORE_STATUS IS '土日祝ステータス考慮しない';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.EMAIL_CREATION_RULE IS 'メール作成ルール';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.SAVE_LOCATION IS '保存先';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.CLIENT_COMPANY_NAME IS '取引先会社名';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.CLIENT_ESTIMATE_DESTINATION IS '取引先見積送付先';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.TYPE_FLAG IS '種別フラグ';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN QUOTATION_CLAIM_SETTING_INFO.LAST_UPDATER IS '最終更新者';

-- 請求減算ルール情報
-- テーブルの削除
DROP TABLE IF EXISTS CLAIM_SUBTRACTION_RULE CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS CLAIM_SUBTRACTION_RULE_SEQ;

-- シークエンスの作成
CREATE SEQUENCE CLAIM_SUBTRACTION_RULE_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE CLAIM_SUBTRACTION_RULE (
    ID INT PRIMARY KEY DEFAULT nextval('CLAIM_SUBTRACTION_RULE_SEQ'),
    SETTING_INFO_ID INT,
    SUBTRACTION_RULE VARCHAR(255),
    SUBTRACTION_ITEM VARCHAR(255),
    SUBTRACTION_AMOUNT VARCHAR(255),
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- 外鍵の追加例
ALTER TABLE CLAIM_SUBTRACTION_RULE ADD CONSTRAINT FK_SETTING_INFO_ID FOREIGN KEY (SETTING_INFO_ID) REFERENCES QUOTATION_CLAIM_SETTING_INFO(ID);

-- テーブルのコメント追加
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.SETTING_INFO_ID IS '設定情報ID';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.SUBTRACTION_RULE IS '減算ルール';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.SUBTRACTION_ITEM IS '減算項目';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.SUBTRACTION_AMOUNT IS '減算額';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.CREATION_DATE IS '作成日';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.CREATOR IS '作成者';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN CLAIM_SUBTRACTION_RULE.LAST_UPDATER IS '最終更新者';



-- 担当者情報テーブル
-- テーブルの削除
DROP TABLE IF EXISTS PERSON_CHARGE_INFO CASCADE;

-- シークエンスの削除
DROP SEQUENCE IF EXISTS PERSON_CHARGE_INFO_SEQ;

-- シークエンスの作成
CREATE SEQUENCE PERSON_CHARGE_INFO_SEQ START WITH 1 INCREMENT BY 1;

-- テーブルの作成
CREATE TABLE PERSON_CHARGE_INFO (
    ID INT PRIMARY KEY DEFAULT nextval('PERSON_CHARGE_INFO_SEQ'),
    LAST_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    PARTNER_STORE_ID INT,
    TYPE_FLAG INT,
    QUOTATION_CLAIM_CREATION_ID INT,
    CREATION_DATE DATE,
    CREATOR VARCHAR(255),
    LAST_UPDATE_DATE DATE,
    LAST_UPDATER VARCHAR(255)
);

-- 注釈の追加
COMMENT ON COLUMN PERSON_CHARGE_INFO.LAST_NAME IS '担当者姓';
COMMENT ON COLUMN PERSON_CHARGE_INFO.FIRST_NAME IS '担当者名';
COMMENT ON COLUMN PERSON_CHARGE_INFO.ADDRESS IS 'アドレス';
COMMENT ON COLUMN PERSON_CHARGE_INFO.PARTNER_STORE_ID IS '取引先店舗ID';
COMMENT ON COLUMN PERSON_CHARGE_INFO.TYPE_FLAG IS '種別フラグ';
COMMENT ON COLUMN PERSON_CHARGE_INFO.QUOTATION_CLAIM_CREATION_ID IS '見積請求作成ID';
COMMENT ON COLUMN PERSON_CHARGE_INFO.CREATION_DATE IS '作成日';
COMMENT ON COLUMN PERSON_CHARGE_INFO.CREATOR IS '作成者';
COMMENT ON COLUMN PERSON_CHARGE_INFO.LAST_UPDATE_DATE IS '最終更新日';
COMMENT ON COLUMN PERSON_CHARGE_INFO.LAST_UPDATER IS '最終更新者';

-- 外鍵の追加
ALTER TABLE PERSON_CHARGE_INFO ADD CONSTRAINT FK_PARTNER_STORE_ID FOREIGN KEY (PARTNER_STORE_ID) REFERENCES BUSINESS_PARTNER_STORE(ID);

